openapi: 3.0.0
info:
  title: Unified Agentic RAG Chatbot System
  version: 1.0.0
  description: API for the agent router that classifies and routes queries to appropriate answering strategies

paths:
  /agent/query:
    post:
      summary: Agent Router Endpoint
      description: Central decision-making endpoint that classifies and routes queries to appropriate answering strategies
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful response from the agent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Bad request - invalid query format
        '500':
          description: Internal server error
      tags:
        - Agent

components:
  schemas:
    QueryRequest:
      type: object
      required:
        - question
      properties:
        question:
          type: string
          description: The user's question
          example: "What are the main themes in this book?"
        selected_text:
          type: string
          description: Specific text selected by the user from the book (triggers selected-text mode)
          example: "The main themes of this book include the struggle between good and evil, the power of friendship, and the importance of perseverance."
        mode:
          type: string
          enum: [selected_text, book, general]
          description: Explicit mode specification (optional, will be inferred if not provided)
          example: "book"

    QueryResponse:
      type: object
      required:
        - answer
        - sources
        - mode
      properties:
        answer:
          type: string
          description: The answer generated by the system
          example: "The main themes in the book are good vs evil, friendship, and perseverance."
        sources:
          type: array
          description: List of document references or citations that support the answer
          items:
            $ref: '#/components/schemas/Source'
        mode:
          type: string
          enum: [selected_text, book, general]
          description: The mode that was used to generate the answer
          example: "book"

    Source:
      type: object
      properties:
        document_id:
          type: string
          description: Unique identifier for the source document
          example: "doc_12345"
        content:
          type: string
          description: The text content from the source document
          example: "The author explores the theme of good versus evil throughout the entire novel..."
        page_number:
          type: integer
          description: The page number in the source document
          example: 45
        section_title:
          type: string
          description: The title of the section in the source document
          example: "Chapter 3: The Battle Begins"

tags:
  - name: Agent
    description: Agent router functionality