"""
Data models for the retrieval-enabled agent service.

This module defines the Pydantic models for all entities in the system,
including requests, responses, and internal data structures.
"""
from datetime import datetime
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from enum import Enum


class UserQuery(BaseModel):
    """
    Represents a user query to the agent system.
    
    Attributes:
        query_id: Unique identifier for the query
        text: The natural language question submitted by the user
        timestamp: When the query was submitted
        user_id: Optional identifier for the user making the query
        session_id: Optional identifier for tracking conversation context
    """
    query_id: str = Field(..., description="Unique identifier for the query")
    text: str = Field(..., description="The natural language question submitted by the user")
    timestamp: datetime = Field(default_factory=datetime.now, description="When the query was submitted")
    user_id: Optional[str] = Field(default=None, description="Optional identifier for the user making the query")
    session_id: Optional[str] = Field(default=None, description="Optional identifier for tracking conversation context")


class RetrievedChunk(BaseModel):
    """
    Represents a chunk of text retrieved from the vector database.
    
    Attributes:
        chunk_id: Unique identifier for the retrieved text chunk
        content: The text content of the retrieved chunk
        url: The source URL of the content in the book
        position: The position of the chunk in the original document
        relevance_score: Similarity score from the retrieval process
        source_metadata: Additional metadata about the source document
    """
    chunk_id: str = Field(..., description="Unique identifier for the retrieved text chunk")
    content: str = Field(..., description="The text content of the retrieved chunk")
    url: str = Field(..., description="The source URL of the content in the book")
    position: int = Field(..., description="The position of the chunk in the original document")
    relevance_score: float = Field(..., description="Similarity score from the retrieval process")
    source_metadata: Dict[str, Any] = Field(..., description="Additional metadata about the source document")


class AgentResponse(BaseModel):
    """
    Represents the final response generated by the agent.
    
    Attributes:
        response_id: Unique identifier for the response
        content: The final answer generated by the agent
        query_id: Reference to the original user query
        chunks_used: List of chunks that were used to generate the response
        timestamp: When the response was generated
        confidence_score: Estimated confidence in the response accuracy
    """
    response_id: str = Field(..., description="Unique identifier for the response")
    content: str = Field(..., description="The final answer generated by the agent")
    query_id: str = Field(..., description="Reference to the original user query")
    chunks_used: List[RetrievedChunk] = Field(..., description="List of chunks that were used to generate the response")
    timestamp: datetime = Field(default_factory=datetime.now, description="When the response was generated")
    confidence_score: Optional[float] = Field(default=None, description="Estimated confidence in the response accuracy")


class AgentSessionStatus(str, Enum):
    """Enumeration for agent session statuses."""
    ACTIVE = "active"
    COMPLETED = "completed"
    EXPIRED = "expired"


class AgentSession(BaseModel):
    """
    Represents an agent session for maintaining conversation context.
    
    Attributes:
        session_id: Unique identifier for the agent session
        created_at: When the session was created
        last_interaction: When the last interaction occurred
        status: Current status of the session
        history: List of previous interactions in the session
    """
    session_id: str = Field(..., description="Unique identifier for the agent session")
    created_at: datetime = Field(default_factory=datetime.now, description="When the session was created")
    last_interaction: datetime = Field(default_factory=datetime.now, description="When the last interaction occurred")
    status: AgentSessionStatus = Field(..., description="Current status of the session")
    history: List[Dict[str, Any]] = Field(..., description="List of previous interactions in the session")


class APIRequest(BaseModel):
    """
    Represents an API request made to the service.
    
    Attributes:
        endpoint: The endpoint being called (e.g., "/ask", "/health", "/agent/run")
        method: HTTP method used
        params: Parameters passed to the endpoint
        headers: HTTP headers for the request
        timestamp: When the request was made
    """
    endpoint: str = Field(..., description="The endpoint being called (e.g., '/ask', '/health', '/agent/run')")
    method: str = Field(..., description="HTTP method used")
    params: Dict[str, Any] = Field(..., description="Parameters passed to the endpoint")
    headers: Dict[str, str] = Field(..., description="HTTP headers for the request")
    timestamp: datetime = Field(default_factory=datetime.now, description="When the request was made")


class APIResponse(BaseModel):
    """
    Represents an API response returned by the service.
    
    Attributes:
        request_id: Reference to the original API request
        status_code: HTTP status code returned
        content: Response data returned by the API
        timestamp: When the response was generated
        processing_time: Time taken to process the request in seconds
    """
    request_id: str = Field(..., description="Reference to the original API request")
    status_code: int = Field(..., description="HTTP status code returned")
    content: Dict[str, Any] = Field(..., description="Response data returned by the API")
    timestamp: datetime = Field(default_factory=datetime.now, description="When the response was generated")
    processing_time: float = Field(..., description="Time taken to process the request in seconds")


# API Request/Response Models for Endpoints

class AskRequest(BaseModel):
    """
    Request model for the /ask endpoint.
    
    Attributes:
        query: The question to ask (required)
        session_id: Session identifier for maintaining context (optional)
        user_id: User identifier (optional)
    """
    query: str = Field(..., description="The question to ask")
    session_id: Optional[str] = Field(default=None, description="Session identifier for maintaining context")
    user_id: Optional[str] = Field(default=None, description="User identifier")


class AskResponse(BaseModel):
    """
    Response model for the /ask endpoint.
    
    Attributes:
        response_id: Unique identifier for the response
        answer: The answer generated by the agent
        sources: List of sources used to generate the answer
        query_id: Reference to the original query
        timestamp: ISO 8601 formatted timestamp
        confidence_score: Estimated confidence in the answer
    """
    response_id: str
    answer: str
    sources: List[RetrievedChunk]
    query_id: str
    timestamp: str
    confidence_score: Optional[float] = None


class HealthResponse(BaseModel):
    """
    Response model for the /health endpoint.
    
    Attributes:
        status: Overall health status (e.g., 'healthy', 'degraded', 'unhealthy')
        timestamp: ISO 8601 formatted timestamp
        services: Status of individual services (OpenAI, Qdrant, Cohere)
        details: Additional details like uptime and active sessions
    """
    status: str
    timestamp: str
    services: Dict[str, Dict[str, Any]]
    details: Dict[str, Any]


class AgentRunRequest(BaseModel):
    """
    Request model for the /agent/run endpoint.
    
    Attributes:
        instructions: Instructions for the agent (required)
        input_data: Additional data to provide to the agent (optional)
        session_id: Session identifier for maintaining context (optional)
        tools: List of specific tools the agent should be allowed to use (optional)
        model: Specific model to use (optional)
    """
    instructions: str
    input_data: Optional[Dict[str, Any]] = None
    session_id: Optional[str] = None
    tools: Optional[List[str]] = None
    model: Optional[str] = None


class ToolCallInfo(BaseModel):
    """
    Information about a tool call made by the agent.
    
    Attributes:
        tool_name: Name of the tool called
        input: Input provided to the tool
        output: Output received from the tool
    """
    tool_name: str
    input: Dict[str, Any]
    output: Dict[str, Any]


class AgentRunResponse(BaseModel):
    """
    Response model for the /agent/run endpoint.
    
    Attributes:
        run_id: Unique identifier for the agent run
        status: Current status of the run
        output: Output generated by the agent
        timestamp: ISO 8601 formatted timestamp
        execution_time_ms: Time taken to execute the run in milliseconds
        tool_calls: List of tool calls made during the run
    """
    run_id: str
    status: str
    output: str
    timestamp: str
    execution_time_ms: int
    tool_calls: List[ToolCallInfo]